name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  crook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --manifest-path crook/Cargo.toml
      - run: cargo build --release --manifest-path crook/Cargo.toml
