name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  herd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
      - run: cargo build --release
